/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FlexiPunkTLD__factory } from "./FlexiPunkTLD__factory";
export { PunkTLD__factory } from "./PunkTLD__factory";
